"""
client/offline_client.py - Local-only operations when the server is unreachable.

Offline mode capabilities:
  - Register:  generate keypair, save locally, queue registration payload
  - Upload:    encrypt file locally, save to offline_records/, queue upload
  - View:      decrypt and open previously downloaded records

Queued operations are stored in offline_records/queue.json
and replayed by the orchestrator when server becomes available.
"""

import json
import uuid
from datetime import datetime
from pathlib import Path
from typing import Optional

from config import OFFLINE_DIR, KEYS_DIR
from core.crypto import (
    generate_keypair, encrypt_document, decrypt_document,
    sha256_file, KeyPair
)
from core.keystore import save_private_key

QUEUE_FILE = OFFLINE_DIR / "queue.json"


# ══════════════════════════════════════════════════════════════════════════════
# Queue helpers
# ══════════════════════════════════════════════════════════════════════════════

def _load_queue() -> list:
    if not QUEUE_FILE.exists():
        return []
    try:
        return json.loads(QUEUE_FILE.read_text(encoding="utf-8"))
    except Exception:
        return []


def _save_queue(queue: list):
    QUEUE_FILE.write_text(json.dumps(queue, indent=2), encoding="utf-8")


def _enqueue(operation: str, payload: dict):
    queue = _load_queue()
    queue.append({
        "id":        str(uuid.uuid4()),
        "operation": operation,
        "payload":   payload,
        "queued_at": datetime.utcnow().isoformat(),
    })
    _save_queue(queue)


def get_pending_queue() -> list:
    return _load_queue()


def clear_queue_item(item_id: str):
    queue = [q for q in _load_queue() if q["id"] != item_id]
    _save_queue(queue)


# ══════════════════════════════════════════════════════════════════════════════
# Offline operations
# ══════════════════════════════════════════════════════════════════════════════

class OfflineClient:

    # ── Registration (offline) ────────────────────────────────────────────────

    def register_local(
        self,
        username: str,
        email: str,
        full_name: str,
        role: str,
        password: str,
        keypair=None,          # KeyPair generated by orchestrator (preferred)
        key_passphrase: str = "",
    ) -> dict:
        """
        Queue registration for when server is back.
        Accepts a keypair generated by the orchestrator so keys are generated once.
        Saves the private key encrypted with key_passphrase.
        """
        if keypair is None:
            keypair = generate_keypair()

        temp_id  = f"offline_{uuid.uuid4().hex[:8]}"

        # Save encrypted key under temp ID
        save_private_key(temp_id, keypair.private_key_pem, key_passphrase)

        reg_payload = {
            "username":              username,
            "email":                 email,
            "full_name":             full_name,
            "role":                  role,
            "password":              password,
            "public_key_hex":        keypair.public_key_hex,
            "public_key_compressed": keypair.public_key_compressed,
            "public_key_hash":       keypair.public_key_hash,
        }
        _enqueue("register", {**reg_payload, "temp_id": temp_id})

        return {
            "user_id":               temp_id,
            "username":              username,
            "email":                 email,
            "full_name":             full_name,
            "role":                  role,
            "public_key_hex":        keypair.public_key_hex,
            "public_key_compressed": keypair.public_key_compressed,
            "public_key_hash":       keypair.public_key_hash,
            "private_key_pem":       keypair.private_key_pem,
            "offline":               True,
            "note":                  "Registration queued — will sync when server is available",
        }

    # ── File upload (offline) ─────────────────────────────────────────────────

    def encrypt_and_store_local(
        self,
        file_bytes: bytes,
        original_filename: str,
        content_type: str,
        patient_id,
        public_key_hex: str,
        private_key_pem: str,
    ) -> dict:
        """
        Encrypt file locally, save to offline_records/, queue the upload.
        Returns metadata dict so the UI can show a record entry immediately.
        """
        result       = encrypt_document(file_bytes, public_key_hex, private_key_pem)
        local_id     = str(uuid.uuid4())
        suffix       = Path(original_filename).suffix or ""
        blob_path    = OFFLINE_DIR / f"{local_id}{suffix}.enc"
        dek_path     = OFFLINE_DIR / f"{local_id}.dek.json"

        blob_path.write_bytes(result["encrypted_blob"])
        dek_path.write_text(json.dumps(result["encrypted_dek"]), encoding="utf-8")

        meta = {
            "local_id":        local_id,
            "patient_id":      patient_id,
            "original_filename": original_filename,
            "content_type":    content_type,
            "content_hash":    result["content_hash"],
            "signature":       result["signature"],
            "blob_path":       str(blob_path),
            "dek_path":        str(dek_path),
            "created_at":      datetime.utcnow().isoformat(),
            "synced":          False,
        }

        _enqueue("upload", meta)
        return {"record_id": local_id, "offline": True, **meta}

    # ── View downloaded record (offline) ──────────────────────────────────────

    def decrypt_local(
        self,
        blob_path: str,
        dek_bundle,
        private_key_pem: str,
    ) -> bytes:
        """
        Decrypt a previously downloaded record from disk.
        blob_path: path to the encrypted blob file.
        dek_bundle: ECIES bundle dict or JSON string.
        """
        encrypted_blob = Path(blob_path).read_bytes()
        return decrypt_document(encrypted_blob, dek_bundle, private_key_pem)

    # ── List locally stored records ───────────────────────────────────────────

    def list_local_records(self, patient_id) -> list:
        """Return queued upload items for this patient as record-like dicts."""
        queue = _load_queue()
        return [
            q["payload"] for q in queue
            if q["operation"] == "upload"
            and str(q["payload"].get("patient_id")) == str(patient_id)
        ]
